2018-01-05 18:21:24.375 7 DEBUG oslo_service.periodic_task [req-74722a6c-65df-4ac1-8f25-adee5953acd6 - - - - -] Running periodic task ContainerStateSyncPeriodicJob.sync_container_state run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:21:24.376 7 DEBUG zun.service.periodic [req-e4615c50-b174-422d-9f17-29fc3dd76304 - - - - -] Start syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:47
2018-01-05 18:21:24.379 7 DEBUG oslo_service.periodic_task [-] Running periodic task Manager.delete_unused_containers run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:21:24.396 7 DEBUG docker.auth [req-e4615c50-b174-422d-9f17-29fc3dd76304 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:21:24.397 7 DEBUG docker.auth [req-e4615c50-b174-422d-9f17-29fc3dd76304 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:21:24.414 7 DEBUG zun.service.periodic [req-e4615c50-b174-422d-9f17-29fc3dd76304 - - - - -] Complete syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:52
2018-01-05 18:21:24.476 7 DEBUG oslo_service.periodic_task [req-e4615c50-b174-422d-9f17-29fc3dd76304 - - - - -] Running periodic task ContainerStateSyncPeriodicJob.inventory_host run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:21:24.485 7 DEBUG oslo_concurrency.processutils [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Running cmd (subprocess): lscpu -p=socket,cpu,online execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-01-05 18:21:24.522 7 DEBUG oslo_concurrency.processutils [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] CMD "lscpu -p=socket,cpu,online" returned: 0 in 0.037s execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-01-05 18:21:24.526 7 DEBUG docker.auth [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:21:24.526 7 DEBUG docker.auth [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:21:24.599 7 DEBUG docker.auth [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:21:24.600 7 DEBUG docker.auth [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:21:24.668 7 DEBUG oslo_concurrency.lockutils [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Lock "compute_resources" acquired by "zun.compute.compute_node_tracker._update_available_resource" :: waited 0.000s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-01-05 18:21:24.669 7 DEBUG docker.auth [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:21:24.669 7 DEBUG docker.auth [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:21:24.754 7 DEBUG zun.compute.compute_node_tracker [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Compute_service record updated for computer5 _update_available_resource /var/lib/kolla/venv/lib/python2.7/site-packages/zun/compute/compute_node_tracker.py:211
2018-01-05 18:21:24.754 7 DEBUG oslo_concurrency.lockutils [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Lock "compute_resources" released by "zun.compute.compute_node_tracker._update_available_resource" :: held 0.086s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-01-05 18:21:25.276 7 DEBUG oslo_service.periodic_task [req-7639cb16-550a-49b7-8fc8-1d10940aafd1 - - - - -] Running periodic task ZunServicePeriodicTasks.update_zun_service run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:21:25.277 7 DEBUG zun.servicegroup.zun_service_periodic [req-aaf47d7b-5a42-43ac-a532-d301e85cf3d4 - - - - -] Update zun_service update_zun_service /var/lib/kolla/venv/lib/python2.7/site-packages/zun/servicegroup/zun_service_periodic.py:40
2018-01-05 18:21:35.805 7 DEBUG zun.compute.manager [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Searching image... image_search /var/lib/kolla/venv/lib/python2.7/site-packages/zun/compute/manager.py:648
2018-01-05 18:21:35.806 7 INFO zun.image.driver [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Loading container image driver 'glance'
2018-01-05 18:21:35.808 7 DEBUG zun.image.glance.driver [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Searching image in glance hadoop search_image /var/lib/kolla/venv/lib/python2.7/site-packages/zun/image/glance/driver.py:118
2018-01-05 18:21:36.178 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'User-Agent: python-glanceclient' -H 'Connection: keep-alive' -H 'X-Auth-Token: {SHA1}de7ba55d8d321d6df6e1d0e03ec9f473645aab99' -H 'Content-Type: application/octet-stream' http://10.141.105.35:9292/v2/images?container_format=docker&limit=20 log_curl_request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-01-05 18:21:36.224 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] GET call to image for http://10.141.105.35:9292/v2/images?container_format=docker&limit=20 used request id req-26e4e321-dddd-4429-8791-57a4aad4aaa4 _request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-01-05 18:21:36.225 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] 
HTTP/1.1 200 OK
Content-Length: 1767
Content-Type: application/json
X-Openstack-Request-Id: req-26e4e321-dddd-4429-8791-57a4aad4aaa4
Date: Fri, 05 Jan 2018 10:21:36 GMT

{"images": [{"status": "active", "virtual_size": null, "name": "hadoop", "tags": [], "container_format": "docker", "created_at": "2018-01-02T07:11:24Z", "size": 6277659648, "disk_format": "qcow2", "updated_at": "2018-01-02T07:12:31Z", "visibility": "public", "locations": [{"url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/snap", "metadata": {}}], "self": "/v2/images/65ffdd17-b469-49c7-80e6-c4cf801388aa", "min_disk": 0, "protected": false, "id": "65ffdd17-b469-49c7-80e6-c4cf801388aa", "file": "/v2/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/file", "checksum": "41a5f951fc5f964db7b5f66de7a5c3f9", "owner": "f91922018dde4c1386972337be79fbee", "direct_url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/snap", "min_ram": 0, "schema": "/v2/schemas/image"}, {"status": "active", "virtual_size": null, "name": "centos", "tags": [], "container_format": "docker", "created_at": "2018-01-02T05:41:11Z", "size": 212088832, "disk_format": "qcow2", "updated_at": "2018-01-02T05:41:15Z", "visibility": "public", "locations": [{"url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36/snap", "metadata": {}}], "self": "/v2/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36", "min_disk": 0, "protected": false, "id": "10a5c4b2-2647-48ec-a0a6-d22e6522be36", "file": "/v2/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36/file", "checksum": "1565a8b9fa4e273495d3f92a16d36ef6", "owner": "f91922018dde4c1386972337be79fbee", "direct_url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36/snap", "min_ram": 0, "schema": "/v2/schemas/image"}], "schema": "/v2/schemas/images", "first": "/v2/images?container_format=docker&limit=20"}
 log_http_response /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-01-05 18:21:36.225 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'User-Agent: python-glanceclient' -H 'Connection: keep-alive' -H 'X-Auth-Token: {SHA1}de7ba55d8d321d6df6e1d0e03ec9f473645aab99' -H 'Content-Type: application/octet-stream' http://10.141.105.35:9292/v2/schemas/image log_curl_request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-01-05 18:21:36.233 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] GET call to image for http://10.141.105.35:9292/v2/schemas/image used request id req-df04563d-a6e6-420c-96d3-78806ef67b4f _request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-01-05 18:21:36.233 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-df04563d-a6e6-420c-96d3-78806ef67b4f
Date: Fri, 05 Jan 2018 10:21:36 GMT

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-01-05 18:21:36.316 7 DEBUG zun.compute.manager [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Creating container: 79a1ba73-e67a-4ae1-a317-ee2572d2f503 _do_container_create /var/lib/kolla/venv/lib/python2.7/site-packages/zun/compute/manager.py:159
2018-01-05 18:21:36.332 7 INFO zun.image.driver [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Loading container image driver 'glance'
2018-01-05 18:21:36.333 7 DEBUG zun.image.glance.driver [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Searching for image hadoop locally _search_image_on_host /var/lib/kolla/venv/lib/python2.7/site-packages/zun/image/glance/driver.py:39
2018-01-05 18:21:36.714 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'User-Agent: python-glanceclient' -H 'Connection: keep-alive' -H 'X-Auth-Token: {SHA1}de7ba55d8d321d6df6e1d0e03ec9f473645aab99' -H 'Content-Type: application/octet-stream' http://10.141.105.35:9292/v2/images?container_format=docker&limit=20 log_curl_request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-01-05 18:21:36.758 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] GET call to image for http://10.141.105.35:9292/v2/images?container_format=docker&limit=20 used request id req-fe7d9519-9eaa-4030-a451-d38ec1a009f6 _request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-01-05 18:21:36.760 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] 
HTTP/1.1 200 OK
Content-Length: 1767
Content-Type: application/json
X-Openstack-Request-Id: req-fe7d9519-9eaa-4030-a451-d38ec1a009f6
Date: Fri, 05 Jan 2018 10:21:37 GMT

{"images": [{"status": "active", "virtual_size": null, "name": "hadoop", "tags": [], "container_format": "docker", "created_at": "2018-01-02T07:11:24Z", "size": 6277659648, "disk_format": "qcow2", "updated_at": "2018-01-02T07:12:31Z", "visibility": "public", "locations": [{"url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/snap", "metadata": {}}], "self": "/v2/images/65ffdd17-b469-49c7-80e6-c4cf801388aa", "min_disk": 0, "protected": false, "id": "65ffdd17-b469-49c7-80e6-c4cf801388aa", "file": "/v2/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/file", "checksum": "41a5f951fc5f964db7b5f66de7a5c3f9", "owner": "f91922018dde4c1386972337be79fbee", "direct_url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/snap", "min_ram": 0, "schema": "/v2/schemas/image"}, {"status": "active", "virtual_size": null, "name": "centos", "tags": [], "container_format": "docker", "created_at": "2018-01-02T05:41:11Z", "size": 212088832, "disk_format": "qcow2", "updated_at": "2018-01-02T05:41:15Z", "visibility": "public", "locations": [{"url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36/snap", "metadata": {}}], "self": "/v2/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36", "min_disk": 0, "protected": false, "id": "10a5c4b2-2647-48ec-a0a6-d22e6522be36", "file": "/v2/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36/file", "checksum": "1565a8b9fa4e273495d3f92a16d36ef6", "owner": "f91922018dde4c1386972337be79fbee", "direct_url": "rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/10a5c4b2-2647-48ec-a0a6-d22e6522be36/snap", "min_ram": 0, "schema": "/v2/schemas/image"}], "schema": "/v2/schemas/images", "first": "/v2/images?container_format=docker&limit=20"}
 log_http_response /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-01-05 18:21:36.760 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] curl -g -i -X GET -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'User-Agent: python-glanceclient' -H 'Connection: keep-alive' -H 'X-Auth-Token: {SHA1}de7ba55d8d321d6df6e1d0e03ec9f473645aab99' -H 'Content-Type: application/octet-stream' http://10.141.105.35:9292/v2/schemas/image log_curl_request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:188
2018-01-05 18:21:36.771 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] GET call to image for http://10.141.105.35:9292/v2/schemas/image used request id req-c0615465-9a8e-4489-9535-3ab19686c75b _request /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:276
2018-01-05 18:21:36.772 7 DEBUG glanceclient.common.http [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] 
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 4157
X-Openstack-Request-Id: req-c0615465-9a8e-4489-9535-3ab19686c75b
Date: Fri, 05 Jan 2018 10:21:37 GMT

{"additionalProperties": {"type": "string"}, "name": "image", "links": [{"href": "{self}", "rel": "self"}, {"href": "{file}", "rel": "enclosure"}, {"href": "{schema}", "rel": "describedby"}], "properties": {"status": {"readOnly": true, "enum": ["queued", "saving", "active", "killed", "deleted", "pending_delete", "deactivated"], "type": "string", "description": "Status of the image"}, "tags": {"items": {"type": "string", "maxLength": 255}, "type": "array", "description": "List of strings related to the image"}, "kernel_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the kernel when booting an AMI-style image.", "is_base": false}, "container_format": {"enum": [null, "ami", "ari", "aki", "bare", "ovf", "ova", "docker"], "type": ["null", "string"], "description": "Format of the container"}, "min_ram": {"type": "integer", "description": "Amount of ram (in MB) required to boot image."}, "ramdisk_id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": ["null", "string"], "description": "ID of image stored in Glance that should be used as the ramdisk when booting an AMI-style image.", "is_base": false}, "locations": {"items": {"required": ["url", "metadata"], "type": "object", "properties": {"url": {"type": "string", "maxLength": 255}, "metadata": {"type": "object"}}}, "type": "array", "description": "A set of URLs to access the image file kept in external store"}, "visibility": {"enum": ["community", "public", "private", "shared"], "type": "string", "description": "Scope of image accessibility"}, "updated_at": {"readOnly": true, "type": "string", "description": "Date and time of the last image modification"}, "owner": {"type": ["null", "string"], "description": "Owner of the image", "maxLength": 255}, "file": {"readOnly": true, "type": "string", "description": "An image file url"}, "min_disk": {"type": "integer", "description": "Amount of disk space (in GB) required to boot image."}, "virtual_size": {"readOnly": true, "type": ["null", "integer"], "description": "Virtual size of image in bytes"}, "id": {"pattern": "^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}$", "type": "string", "description": "An identifier for the image"}, "size": {"readOnly": true, "type": ["null", "integer"], "description": "Size of image file in bytes"}, "instance_uuid": {"type": "string", "description": "Metadata which can be used to record which instance this image is associated with. (Informational only, does not create an instance snapshot.)", "is_base": false}, "os_distro": {"type": "string", "description": "Common name of operating system distribution as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "name": {"type": ["null", "string"], "description": "Descriptive name for the image", "maxLength": 255}, "checksum": {"readOnly": true, "type": ["null", "string"], "description": "md5 hash of image contents.", "maxLength": 32}, "created_at": {"readOnly": true, "type": "string", "description": "Date and time of image registration"}, "disk_format": {"enum": [null, "ami", "ari", "aki", "vhd", "vhdx", "vmdk", "raw", "qcow2", "vdi", "iso", "ploop"], "type": ["null", "string"], "description": "Format of the disk"}, "os_version": {"type": "string", "description": "Operating system version as specified by the distributor", "is_base": false}, "protected": {"type": "boolean", "description": "If true, image will not be deletable."}, "architecture": {"type": "string", "description": "Operating system architecture as specified in https://docs.openstack.org/python-glanceclient/latest/cli/property-keys.html", "is_base": false}, "direct_url": {"readOnly": true, "type": "string", "description": "URL to access the image file kept in external store"}, "self": {"readOnly": true, "type": "string", "description": "An image self url"}, "schema": {"readOnly": true, "type": "string", "description": "An image schema url"}}}
 log_http_response /var/lib/kolla/venv/lib/python2.7/site-packages/glanceclient/common/http.py:202
2018-01-05 18:21:36.775 7 DEBUG zun.image.glance.utils [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Found matches [{u'status': u'active', u'tags': [], u'container_format': u'docker', u'min_ram': 0, u'updated_at': u'2018-01-02T07:12:31Z', u'visibility': u'public', u'locations': [{u'url': u'rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/snap', u'metadata': {}}], u'owner': u'f91922018dde4c1386972337be79fbee', u'file': u'/v2/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/file', u'min_disk': 0, u'virtual_size': None, u'id': u'65ffdd17-b469-49c7-80e6-c4cf801388aa', u'size': 6277659648, u'name': u'hadoop', u'checksum': u'41a5f951fc5f964db7b5f66de7a5c3f9', u'created_at': u'2018-01-02T07:11:24Z', u'disk_format': u'qcow2', u'protected': False, u'direct_url': u'rbd://e1250bb7-1f23-4cd4-8919-64b1ffa37b96/images/65ffdd17-b469-49c7-80e6-c4cf801388aa/snap', u'schema': u'/v2/schemas/image'}]  find_image /var/lib/kolla/venv/lib/python2.7/site-packages/zun/image/glance/utils.py:39
2018-01-05 18:21:48.425 7 DEBUG docker.auth [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:21:48.427 7 DEBUG docker.auth [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:21:48.428 7 DEBUG zun.container.docker.driver [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Reading local tar image /var/lib/zun/images/65ffdd17-b469-49c7-80e6-c4cf801388aa.tar  read_tar_image /var/lib/kolla/venv/lib/python2.7/site-packages/zun/container/docker/driver.py:110
2018-01-05 18:21:48.459 7 DEBUG oslo_concurrency.lockutils [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Lock "compute_resources" acquired by "zun.compute.compute_node_tracker.container_claim" :: waited 0.000s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-01-05 18:21:48.467 7 DEBUG docker.auth [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:21:48.468 7 DEBUG docker.auth [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:21:48.532 7 DEBUG oslo_concurrency.lockutils [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Lock "compute_resources" released by "zun.compute.compute_node_tracker.container_claim" :: held 0.073s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-01-05 18:21:48.533 7 DEBUG docker.auth [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:21:48.534 7 DEBUG docker.auth [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:21:48.548 7 DEBUG zun.container.docker.driver [req-66188b1e-6994-4a2c-a7f2-39b2443b4943 56cfd9b3cf7f4f7f81dc8916638c7324 f91922018dde4c1386972337be79fbee default - -] Creating container with image hadoop name test2 create /var/lib/kolla/venv/lib/python2.7/site-packages/zun/container/docker/driver.py:122
2018-01-05 18:22:24.754 7 DEBUG oslo_service.periodic_task [req-e9c78378-f016-452d-a9bc-7743a4381109 - - - - -] Running periodic task ContainerStateSyncPeriodicJob.inventory_host run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:22:24.766 7 DEBUG oslo_concurrency.processutils [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Running cmd (subprocess): lscpu -p=socket,cpu,online execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-01-05 18:22:24.798 7 DEBUG oslo_concurrency.processutils [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] CMD "lscpu -p=socket,cpu,online" returned: 0 in 0.032s execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-01-05 18:22:24.802 7 DEBUG docker.auth [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:22:24.802 7 DEBUG docker.auth [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:22:24.871 7 DEBUG docker.auth [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:22:24.871 7 DEBUG docker.auth [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:22:24.947 7 DEBUG oslo_concurrency.lockutils [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Lock "compute_resources" acquired by "zun.compute.compute_node_tracker._update_available_resource" :: waited 0.000s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-01-05 18:22:24.948 7 DEBUG docker.auth [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:22:24.948 7 DEBUG docker.auth [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:22:25.048 7 DEBUG zun.compute.compute_node_tracker [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Compute_service record updated for computer5 _update_available_resource /var/lib/kolla/venv/lib/python2.7/site-packages/zun/compute/compute_node_tracker.py:211
2018-01-05 18:22:25.049 7 DEBUG oslo_concurrency.lockutils [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Lock "compute_resources" released by "zun.compute.compute_node_tracker._update_available_resource" :: held 0.102s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-01-05 18:22:25.286 7 DEBUG oslo_service.periodic_task [req-aaf47d7b-5a42-43ac-a532-d301e85cf3d4 - - - - -] Running periodic task ZunServicePeriodicTasks.update_zun_service run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:22:25.287 7 DEBUG zun.servicegroup.zun_service_periodic [req-320f2435-3183-4e8b-8c3a-1b5894695260 - - - - -] Update zun_service update_zun_service /var/lib/kolla/venv/lib/python2.7/site-packages/zun/servicegroup/zun_service_periodic.py:40
2018-01-05 18:22:25.376 7 DEBUG oslo_service.periodic_task [-] Running periodic task Manager.delete_unused_containers run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:22:26.670 7 DEBUG oslo_service.periodic_task [req-b6aa4860-c011-4421-99e4-30820bab3428 - - - - -] Running periodic task ContainerStateSyncPeriodicJob.sync_container_state run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:22:26.671 7 DEBUG zun.service.periodic [req-f8c2edc4-3021-4a51-82f3-9138f8fd684f - - - - -] Start syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:47
2018-01-05 18:22:26.687 7 DEBUG docker.auth [req-f8c2edc4-3021-4a51-82f3-9138f8fd684f - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:22:26.687 7 DEBUG docker.auth [req-f8c2edc4-3021-4a51-82f3-9138f8fd684f - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:22:26.707 7 DEBUG zun.service.periodic [req-f8c2edc4-3021-4a51-82f3-9138f8fd684f - - - - -] Complete syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:52
2018-01-05 18:23:26.277 7 DEBUG oslo_service.periodic_task [req-320f2435-3183-4e8b-8c3a-1b5894695260 - - - - -] Running periodic task ZunServicePeriodicTasks.update_zun_service run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:23:26.278 7 DEBUG zun.servicegroup.zun_service_periodic [req-9a75c4d9-8291-4da8-86d9-9ccafc542de3 - - - - -] Update zun_service update_zun_service /var/lib/kolla/venv/lib/python2.7/site-packages/zun/servicegroup/zun_service_periodic.py:40
2018-01-05 18:23:26.376 7 DEBUG oslo_service.periodic_task [-] Running periodic task Manager.delete_unused_containers run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:23:26.476 7 DEBUG oslo_service.periodic_task [req-f8c2edc4-3021-4a51-82f3-9138f8fd684f - - - - -] Running periodic task ContainerStateSyncPeriodicJob.inventory_host run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:23:26.484 7 DEBUG oslo_concurrency.processutils [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Running cmd (subprocess): lscpu -p=socket,cpu,online execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-01-05 18:23:26.522 7 DEBUG oslo_concurrency.processutils [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] CMD "lscpu -p=socket,cpu,online" returned: 0 in 0.038s execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-01-05 18:23:26.525 7 DEBUG docker.auth [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:23:26.526 7 DEBUG docker.auth [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:23:26.596 7 DEBUG docker.auth [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:23:26.597 7 DEBUG docker.auth [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:23:26.672 7 DEBUG oslo_concurrency.lockutils [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Lock "compute_resources" acquired by "zun.compute.compute_node_tracker._update_available_resource" :: waited 0.000s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-01-05 18:23:26.672 7 DEBUG docker.auth [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:23:26.673 7 DEBUG docker.auth [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:23:26.759 7 DEBUG zun.compute.compute_node_tracker [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Compute_service record updated for computer5 _update_available_resource /var/lib/kolla/venv/lib/python2.7/site-packages/zun/compute/compute_node_tracker.py:211
2018-01-05 18:23:26.759 7 DEBUG oslo_concurrency.lockutils [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Lock "compute_resources" released by "zun.compute.compute_node_tracker._update_available_resource" :: held 0.087s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-01-05 18:23:27.659 7 DEBUG oslo_service.periodic_task [req-6a0aaedb-a266-4f8a-8681-6c8fe3dd5412 - - - - -] Running periodic task ContainerStateSyncPeriodicJob.sync_container_state run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:23:27.660 7 DEBUG zun.service.periodic [req-1f856653-3955-42a9-a06c-5b1918462dd5 - - - - -] Start syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:47
2018-01-05 18:23:27.676 7 DEBUG docker.auth [req-1f856653-3955-42a9-a06c-5b1918462dd5 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:23:27.677 7 DEBUG docker.auth [req-1f856653-3955-42a9-a06c-5b1918462dd5 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:23:27.695 7 DEBUG zun.service.periodic [req-1f856653-3955-42a9-a06c-5b1918462dd5 - - - - -] Complete syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:52
2018-01-05 18:24:26.385 7 DEBUG oslo_service.periodic_task [-] Running periodic task Manager.delete_unused_containers run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:24:28.276 7 DEBUG oslo_service.periodic_task [req-9a75c4d9-8291-4da8-86d9-9ccafc542de3 - - - - -] Running periodic task ZunServicePeriodicTasks.update_zun_service run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:24:28.277 7 DEBUG zun.servicegroup.zun_service_periodic [req-e075c78c-6493-4aa9-b3ca-c8eb9885aa3a - - - - -] Update zun_service update_zun_service /var/lib/kolla/venv/lib/python2.7/site-packages/zun/servicegroup/zun_service_periodic.py:40
2018-01-05 18:24:28.375 7 DEBUG oslo_service.periodic_task [req-1f856653-3955-42a9-a06c-5b1918462dd5 - - - - -] Running periodic task ContainerStateSyncPeriodicJob.sync_container_state run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:24:28.376 7 DEBUG zun.service.periodic [req-a90a71ec-c07e-49cd-9dd1-70b2ed772954 - - - - -] Start syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:47
2018-01-05 18:24:28.391 7 DEBUG docker.auth [req-a90a71ec-c07e-49cd-9dd1-70b2ed772954 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:24:28.392 7 DEBUG docker.auth [req-a90a71ec-c07e-49cd-9dd1-70b2ed772954 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:24:28.410 7 DEBUG zun.service.periodic [req-a90a71ec-c07e-49cd-9dd1-70b2ed772954 - - - - -] Complete syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:52
2018-01-05 18:24:28.476 7 DEBUG oslo_service.periodic_task [req-a90a71ec-c07e-49cd-9dd1-70b2ed772954 - - - - -] Running periodic task ContainerStateSyncPeriodicJob.inventory_host run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:24:28.486 7 DEBUG oslo_concurrency.processutils [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Running cmd (subprocess): lscpu -p=socket,cpu,online execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-01-05 18:24:28.517 7 DEBUG oslo_concurrency.processutils [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] CMD "lscpu -p=socket,cpu,online" returned: 0 in 0.032s execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-01-05 18:24:28.521 7 DEBUG docker.auth [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:24:28.521 7 DEBUG docker.auth [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:24:28.587 7 DEBUG docker.auth [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:24:28.588 7 DEBUG docker.auth [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:24:28.670 7 DEBUG oslo_concurrency.lockutils [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Lock "compute_resources" acquired by "zun.compute.compute_node_tracker._update_available_resource" :: waited 0.000s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-01-05 18:24:28.671 7 DEBUG docker.auth [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:24:28.672 7 DEBUG docker.auth [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:24:28.760 7 DEBUG zun.compute.compute_node_tracker [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Compute_service record updated for computer5 _update_available_resource /var/lib/kolla/venv/lib/python2.7/site-packages/zun/compute/compute_node_tracker.py:211
2018-01-05 18:24:28.760 7 DEBUG oslo_concurrency.lockutils [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Lock "compute_resources" released by "zun.compute.compute_node_tracker._update_available_resource" :: held 0.090s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
2018-01-05 18:25:26.396 7 DEBUG oslo_service.periodic_task [-] Running periodic task Manager.delete_unused_containers run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:25:28.659 7 DEBUG oslo_service.periodic_task [req-08bea7a3-54a1-47fc-9a14-2bdecdc4abec - - - - -] Running periodic task ContainerStateSyncPeriodicJob.sync_container_state run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:25:28.660 7 DEBUG zun.service.periodic [req-4669a30c-9921-400b-aa2b-540daa6f307b - - - - -] Start syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:47
2018-01-05 18:25:28.676 7 DEBUG docker.auth [req-4669a30c-9921-400b-aa2b-540daa6f307b - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:25:28.677 7 DEBUG docker.auth [req-4669a30c-9921-400b-aa2b-540daa6f307b - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:25:28.695 7 DEBUG zun.service.periodic [req-4669a30c-9921-400b-aa2b-540daa6f307b - - - - -] Complete syncing container states. sync_container_state /var/lib/kolla/venv/lib/python2.7/site-packages/zun/service/periodic.py:52
2018-01-05 18:25:30.278 7 DEBUG oslo_service.periodic_task [req-e075c78c-6493-4aa9-b3ca-c8eb9885aa3a - - - - -] Running periodic task ZunServicePeriodicTasks.update_zun_service run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:25:30.279 7 DEBUG zun.servicegroup.zun_service_periodic [req-5c145df2-b656-4734-a779-5ac9720e1fcc - - - - -] Update zun_service update_zun_service /var/lib/kolla/venv/lib/python2.7/site-packages/zun/servicegroup/zun_service_periodic.py:40
2018-01-05 18:25:30.476 7 DEBUG oslo_service.periodic_task [req-4669a30c-9921-400b-aa2b-540daa6f307b - - - - -] Running periodic task ContainerStateSyncPeriodicJob.inventory_host run_periodic_tasks /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_service/periodic_task.py:215
2018-01-05 18:25:30.486 7 DEBUG oslo_concurrency.processutils [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] Running cmd (subprocess): lscpu -p=socket,cpu,online execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:367
2018-01-05 18:25:30.525 7 DEBUG oslo_concurrency.processutils [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] CMD "lscpu -p=socket,cpu,online" returned: 0 in 0.039s execute /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/processutils.py:404
2018-01-05 18:25:30.529 7 DEBUG docker.auth [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:25:30.529 7 DEBUG docker.auth [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:25:30.603 7 DEBUG docker.auth [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:25:30.603 7 DEBUG docker.auth [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:25:30.677 7 DEBUG oslo_concurrency.lockutils [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] Lock "compute_resources" acquired by "zun.compute.compute_node_tracker._update_available_resource" :: waited 0.000s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:270
2018-01-05 18:25:30.678 7 DEBUG docker.auth [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg'] find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:234
2018-01-05 18:25:30.678 7 DEBUG docker.auth [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] No config file found find_config_file /var/lib/kolla/venv/lib/python2.7/site-packages/docker/auth.py:241
2018-01-05 18:25:30.776 7 DEBUG zun.compute.compute_node_tracker [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] Compute_service record updated for computer5 _update_available_resource /var/lib/kolla/venv/lib/python2.7/site-packages/zun/compute/compute_node_tracker.py:211
2018-01-05 18:25:30.777 7 DEBUG oslo_concurrency.lockutils [req-e0807ea5-a8dd-4ebe-a7c1-6bfb5b2c7c28 - - - - -] Lock "compute_resources" released by "zun.compute.compute_node_tracker._update_available_resource" :: held 0.100s inner /var/lib/kolla/venv/lib/python2.7/site-packages/oslo_concurrency/lockutils.py:282
